version: "3.9"

services:
  brobot:
    build: .
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - GUILD_ID=$GUILD_ID
      - ADMIN_IDS=$ADMIN_IDS
      - MEMBER_CHANNEL_ID=$MEMBER_CHANNEL_ID
      - REDDIT_API_CLIENT_ID=$REDDIT_API_CLIENT_ID
      - REDDIT_API_CLIENT_SECRET=$REDDIT_API_CLIENT_SECRET
      - GAME_API_ENDPOINT=$GAME_API_ENDPOINT
      - beta=$beta
      - REDIS_ENDPOINT=redis
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256m
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 126m


volumes:
  redis_data:
