version: "3.9"

services:
  brobot:
    build: .
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - GUILD_ID=$GUILD_ID
      - MEMBER_CHANNEL_ID=$MEMBER_CHANNEL_ID
      - WORDLE_CHANNEL_ID=$WORDLE_CHANNEL_ID
      - REDDIT_API_CLIENT_ID=$REDDIT_API_CLIENT_ID
      - REDDIT_API_CLIENT_SECRET=$REDDIT_API_CLIENT_SECRET
      - GAME_API_ENDPOINT=$GAME_API_ENDPOINT
      - REDIS_ENDPOINT=redis
  db:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 126m


volumes:
  redis_data: